name: blogbuild
dependencies:
- dateutil
- distribute=0.6.45=py27_1
- freetype
- hyde=0.8.5=py27_0
- ipython
- ipython-notebook
- jinja2=2.7.3=py27_1
- libpng=1.5.13=1
- libsodium=0.4.5=0
- markdown=2.3.1=py27_0
- markupsafe=0.18=py27_0
- matplotlib=1.3.1=np18py27_1
- numpy=1.8.1=py27_0
- openssl=1.0.1h=0
- pip=1.5.6=py27_0
- pygments=1.6=py27_0
- pyparsing=2.0.1=py27_0
- python=2.7.8=1
#- python.app=1.2=py27_3
- pytz=2014.4=py27_0
- pyyaml=3.11=py27_0
- pyzmq=14.3.1=py27_0
- readline=6.2=2
- scikit-learn=0.15.0=np18py27_0
- scipy=0.14.0=np18py27_0
- setuptools=5.7=py27_0
- six=1.7.3=py27_0
- sqlite=3.8.4.1=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.15=0
- tornado=4.0.1=py27_0
- yaml
- zeromq=4.0.4=0
- zlib=1.2.7=1
- pip:
  - astroml==0.2
  - astroml-addons==0.2.1
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.2
  - blinker==1.3
  - commando==0.3.4
  - docutils==0.12
  - doit==0.26.0
  - feedgenerator==1.7
  - fswrap==0.1.2
  - logbook==0.7.0
  - lxml==3.4.0
  - macfsevents==0.3
  - mako==1.0.0
  - natsort==3.5.0
  - nikola==7.1.0
  - pelican==3.3
  - pillow==2.5.3
  - pyrss2gen==1.1
  - python-dateutil==2.2
  - requests==2.3.0
  - smartypants==1.6.0.3
  - typogrify==2.0.0
  - unidecode==0.04.16
  - wikipedia==1.3.1
  - wsgiref==0.1.2
  - yapsy==1.10.423

