name: blogbuild
channels:
  - defaults
dependencies:
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - scipy=1.4.1
  - theano=1.0.4

